name: Bug Report
description: Create a bug report to help improve Google Assistant Unofficial Desktop Client 
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        <!--Thanks for taking the time to fill out this bug report!-->
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '....'
        2. Click on '....'
        3. Scroll down to '....'
        4. See the error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: assistant-version
    attributes:
      label: Assistant Version
      description: What version of the Assistant are you using?
      placeholder: v1.0.0-rc.2
    validations:
      required: true
  - type: input
    attributes:
      label: OS & Version
      description: What OS & Version are you using?
      placeholder: e.g. Windows 10 20H2 19042.804
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant Assets
      description: |
        A list of assets (logs, screenshots) relevant to this bug.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: |
