name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug]
assignees:
- Melvin-Abraham

body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!

- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: A detailed and clear concise description of the bug:
    placeholder: "Bug description:"
    value: "What happened in the bug:"
  validations:
    required: true
- type: textarea
  id: expectations
  atttributes:
    label: What did you expect to happen?
    description: A detailed and concise description of what you expected to happen:
    placeholder: "What you expected to happen:"
    value: "Eg: Expected to see this..."
  
- type: dropdown
  id: assistant-version
  attributes:
    label: Version
    description: What version of Google Assistant are you running?
    options:
    - 1.0.0-rc.2
    - 1.0.0-rc.1
    - 1.0.0
    - Compiled from codebase
  validations:
    required: true
- - type: input
      attributes:
        label: OS & Version
        description: What OS & Version are you using?
        placeholder: e.g. Windows 10 20H2 19042.804
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant Assets
      description: |
        A list of assets (logs, screenshots) relevant to this bug.
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
