name: Bug Report
description: File a bug report and help to improve Google Assistant Unofficial Desktop Client
title: "[Bug]: "
labels: [bug]
assignees:
- Melvin-Abraham

body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: markdown
  value: "Please check if this issue is mentioned in the [FAQs](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ))
- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: "A detailed and clear concise description of the bug:"
    placeholder: "Bug description:"
    value: "What happened in the bug:"
  validations:
    required: true
- type: textarea
  id: expectations
  attributes:
    label: What did you expect to happen?
    description: "A detailed and concise description of what you expected to happen:"
    placeholder: "What you expected to happen:"
    value: "Eg: Expected to see this..."
  
- type: dropdown
  id: assistant-version
  attributes:
    label: Version
    description: "What version of Google Assistant are you running?"
    options:
    - 1.0.0-rc.2
    - 1.0.0-rc.1
    - 1.0.0
    - Compiled from codebase
  validations:
    required: true
    
- type: textarea
  id: os-version
  attributes:
    label: What is your OS and it's version?
    description: "Your OS version:"
    placeholder: "What is your OS?"
    value: "Eg: Windows 10 2004 Build 19042/MacOS Big Sur 11.2/Ubuntu 20.04 LTS"
  validations:
    required: true
- type: textarea
  attributes:
    label: Relevant Assets
    description: |
      "A list of assets (logs, screenshots) relevant to this bug."
      "Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in."
