blank_issues_enabled: true
contact_links:
  - name: Question
    url: https://github.com/Melvin-Abraham/Google-Assistant/Unofficial-Desktop-Client/discussions/new
    about: Please ask and answer questions here.
