name: Feature Request
description: Suggest an idea you have in mind for this project
title: "[💡 Feature Request]: "
labels: ["✨ enhancement"]
assignees:
  - Melvin-Abraham

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an idea for this project!

        🔍 Before you proceed, make sure to search [existing issues](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues) to avoid creating duplicates.
        💡 Limit this issue to not more than **one feature request** for clarity and discoverability.
        ✨ Keep the issue concise and clear as much as possible.

  - type: textarea
    id: problem-description
    attributes:
      label: What's the Problem?
      description: If your feature request is related to a problem, describe it clearly.
      placeholder: "Eg: I'm always frustrated when [...]"

  - type: textarea
    id: feature-idea
    attributes:
      label: What's your solution or idea?
      description: "A clear and concise description of what you want to happen"
      placeholder: "Eg: I would like the assistant to ..."
    validations:
      required: true

  - type: textarea
    id: feature-alternatives
    attributes:
      label: Alternatives Considered
      description: "Describe alternatives you've considered"
      placeholder: "Eg: I have considered ... as an alternative to this issue"
    validations:
      required: true

  - type: dropdown
    id: assistant-version
    attributes:
      label: App Version
      description: "What version of Google Assistant are you running?"
      options:
        - Built from source
        - v1.0.0-rc.2
        - v1.0.0-rc.1
        - v1.0.0-beta
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: "The version and build of the Operating System on which you are running this application"
      placeholder: "Eg: Windows 10 2004 Build 19042 / MacOS Big Sur 11.2 / Ubuntu 20.04 LTS"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: "Add any other comment or screenshots about the feature request here."
      placeholder: "Any additional context or screenshots"

  - type: checkboxes
    id: feature-request-issue-checklist
    attributes:
      label: Pre-submission Checklist
      description: Mark the checkboxes accordingly to continue submitting this feature request
      options:
        - label: "I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%E2%9C%A8+enhancement%22+) and didn't find any duplicate issue"
          required: true
        - label: "This issue only covers one particular feature request"
          required: true
