export interface AssistantAppConfig {
  keyFilePath: string,
  savedTokensPath: string,
  forceNewConversation: boolean,
  enableAudioOutput: boolean,
  enableAudioOutputForTypedQueries: boolean,
  enableMicOnImmediateResponse: boolean,
  startAsMaximized: boolean,
  windowFloatBehavior: 'normal' | 'always-on-top' | 'close-on-blur',
  escapeKeyBehavior: 'none' | 'minimize' | 'close',
  microphoneSource: string,
  speakerSource: string,
  displayPreference: string,
  windowBorder: 'none' | 'minimal' | 'prominent' | 'color-shift',
  launchAtStartup: boolean,
  alwaysCloseToTray: boolean,
  enablePingSound: boolean,
  enableAutoScaling: boolean,
  enableMicOnStartup: boolean,
  respondToHotword: boolean,
  hideOnFirstLaunch: boolean,
  notifyOnStartup: boolean,
  assistantHotkey: string,
  hotkeyBehavior: 'launch' | 'launch+mic' | 'launch+close',
  language: string,
  theme: string,
  autoDownloadUpdates: boolean,
  [key: string]: any,
}
