let themes = {
    "dark-theme": {
        "--window-border-radius": "20px",
        "--color-blue": "#1e90ff",
        "--color-red": "#ea4335",
        "--color-green": "#34a853",
        "--color-yellow": "#fbbc05",
        "--color-bg": "#121212",
        "--color-secondary": "#ffffff1c",
        "--color-fg-rgb": "255, 255, 255",
        "--color-fg": "#ffffff",
        "--color-fg-med": "#ffffff80",
        "--color-fg-med-low": "#ffffff40",
        "--color-fg-light": "#ffffff1c",
        "--color-fg-lightest": "#ffffff0d",
        "--color-btn-bg-default": "#ffffff14",
        "--color-btn-bg-hover": "#ffffff24",
        "--color-btn-bg-active": "#ffffff0d",
        "--color-suggestion-bg": "#ffffff0d",
        "--color-suggestion-fg": "#ffffff",
        "--color-suggestion-border-default": "transparent",
        "--color-suggestion-border-hover": "#ffffff80",
        "--color-suggestion-border-active": "#ffffff40",
        "--switch-bg": "#ffffff40",
        "--color-loader-bg": "#272727",
        "--color-input-border": "#ffffff1a",
        "--opacity-input-border-low": "0.502",
        "--opacity-input-border-high": "0.749",
        "--color-scrollbar-bg": "#0D0D0D",
        "--color-scrollbar-response-screen-bg": "#0D0D0D",
        "--color-scrollbar-response-screen-fg-rgb": "255, 255, 255",
        "--color-select-bg": "transparent",
        "--color-select-bg-hover": "#ffffff0d",
        "--color-select-border": "#ffffff40",
        "--color-option-bg": "#000000"
    },

    "light-theme": {
        "--window-border-radius": "20px",
        "--color-blue": "#1e90ff",
        "--color-red": "#ea4335",
        "--color-green": "#34a853",
        "--color-yellow": "#fbbc05",
        "--color-bg": "#eeeeee",
        "--color-secondary": "#000000a9",
        "--color-fg-rgb": "0, 0, 0",
        "--color-fg": "#000000",
        "--color-fg-med": "#00000080",
        "--color-fg-med-low": "#00000040",
        "--color-fg-light": "#0000001c",
        "--color-fg-lightest": "#0000000d",
        "--color-btn-bg-default": "#00000014",
        "--color-btn-bg-hover": "#00000024",
        "--color-btn-bg-active": "#0000000d",
        "--color-suggestion-bg": "transparent",
        "--color-suggestion-fg": "#000000cc",
        "--color-suggestion-border-default": "#00000040",
        "--color-suggestion-border-hover": "#00000080",
        "--color-suggestion-border-active": "#00000020",
        "--switch-bg": "#00000040",
        "--color-loader-bg": "#0000001c",
        "--color-input-border": "#00000040",
        "--opacity-input-border-low": "0.7",
        "--opacity-input-border-high": "1",
        "--color-scrollbar-bg": "#ffffff",
        "--color-scrollbar-response-screen-bg": "#000000",
        "--color-scrollbar-response-screen-fg-rgb": "255, 255, 255",
        "--color-select-bg": "transparent",
        "--color-select-bg-hover": "#0000000d",
        "--color-select-border": "#00000040",
        "--color-option-bg": "inherit"
    }
}
